---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
  labels:
    name: chaos-testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-poc
  namespace: chaos-testing
  labels:
    app: chaos-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-poc
  template:
    metadata:
      labels:
        app: chaos-poc
    spec:
      containers:
        - name: chaos-poc
          image: 824778207220.dkr.ecr.ap-south-1.amazonaws.com/chaos_poc:7
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-poc-service
  namespace: chaos-testing
  labels:
    app: chaos-poc
spec:
  type: LoadBalancer
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: chaos-poc
